name: "Deploy React + Vite to Github Pages"

on:
  push:
    branches: -main

jobs:
  build-deploy:
    runs-on: ubantu-latest # https://github.com/actions/runner-images

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3 # https://github.com/actions/checkout

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependecies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy to github pages --> https://github.com/peaceiris/actions-gh-pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
